### ISSUE TITLE
Ability to prepend ALL log messages

### ISSUE THREAD

**Issue by ashleyryan** [mperdeck/jsnlog.js#21]
Hi,

I'm looking for the ability to define a function that appends/prepends all log messages with some user data that is only available on the client side. Maybe another setOptions property. I was hoping I could get the body of the XmlHttpRequest in beforeSend, but it's not available there.

The closest I can find is adding a header with the data I want to send, but then I'm not sure how to get log4net to use that header data. I've looked into the EmptyLog4Net - beforeSend project, but the customer header doesn't appear to be used anywhere after it's sent.

Thanks, 
Ashley

**Comment by tparnell8** [comment]
:+1:  hooks both in .NET artifacts and JS where we can prepend things to the log message string would be awesome

some thoughts...

For javascript SPA's logging what modules were loaded, and the current state of the application would be helpful for debugging

For .NET: The ability to append any information that came through in the request like session tokens, cookies, etc. any data in HttpContext would also be good to log.

**Comment by mperdeck** [comment]
I agree that hooks in both the client and server ends would be useful. Haven't implemented this yet due to lack of time.

On the client site, I'm planning to have an option "beforeLog" on Loggers. This would be inherited just like any other Logger option. It would take a function which takes the original log message (or object) and returns the message to be logged to the server. This would allow you to add whatever you want.
http://jsnlog.com/Documentation/JSNLogJs/Logger/SetOptions

On the server side, I'm looking at adding a method or property to the JavascriptLogging class that would allow you to set a method that takes the incoming HttpRequest and message and allows you to modify the message.
http://jsnlog.com/Documentation/JavascriptLogging

Any feedback would be welcome.

**Comment by tparnell8** [comment]
So I think that sounds like exactly what we are looking for. I am willing to help make this happen if you can point me in the right direction. What I would like to see is in .NET accessing the transforms through a delegate (perhaps even an event handler?) , and the same in javascript though a function.

Just to give you some context. We work at Vistaprint, and we have been using jsnlog for wiring up our client side logging to our log4net infrastructure, and it has been a pretty amazing journey already. Our application is not root of our url, we sit in a virtual sub directory, and altering the jsnlog ajax url was super simple, and flexible. We get jsnlog through commonjs modules client side, and use browserify to wire the whole thing together. Our responsibilities mostly lay in client side code, and I think other teams at vistaprint may adopt jsnlog, because of the success we had with it (infact I have been evangelizing it). So far we like it, and if donations will help keep this project going, I may be able to make it happen. I'm also willing to put in time to work on this project, as I believe this solves a big hole in a lot of ecosystems.

One thing to keep in mind is that HttpModules are slowely leaving the ecosystem with things like ASP.NET 5 middle wear (and the original OWIN middlewear), so at some point in the journey jsnlog may need to convert to a middlewear component. I have written some [middlewear components](https://github.com/tparnell8/TurboLinks.Net) already and its pretty simple.

**Comment by mperdeck** [comment]
Thanks for the kind words! Good to see that my baby is doing good things out there.

I would welcome pull requests for the hooks the two of you have been proposing. And any other features for which you see a good business case in the wider community (that is, not just for your particular situation).

You will have noticed that JSNLog sits in a couple of projects on Github, including:
jsnlog.js (client side component) - https://github.com/mperdeck/jsnlog.js
jsnlog (.Net server side component) - https://github.com/mperdeck/jsnlog
solution with working demos - https://github.com/mperdeck/jsnlogSimpleWorkingDemos
jsnlog.com web site - https://github.com/mperdeck/jsnlog.website

Implementing a new feature means 
1) updating jsnlog.js or jsnlog, but also 
2) adding a working demo. You can do this as part of your testing. 
3) Plus documentation needs to be added on the web site (I always do this myself). 

Please note that 
* jsnlog.js is actually written in TypeScript (in jsnlog.ts). So any client side changes need to be to jsnlog.ts. 
* Backward compatibility is crucial.
* Code changes need to jive with the existing (imperfect) architecture, so I don't lose track how it all hangs together.

I am painfully aware that OWIN and ASP.NET 5 are coming. I have some ideas on how to adapt JSNLog to this new world, but it will require some big changes to the server side because that is currently tightly coupled to having the configuration as XML in the web.config. If that would interest you, please have a look at the existing code (in the jsnlog project) and let me know your thoughts.

Currently, what JSNLog really needs in my view is exposure. 25000 downloads on Nuget is not bad, but not massive either. Any help in making it better known would be great.
